### ISSUE TITLE
[builder] conversion issue (ENV)

### ISSUE THREAD

**Issue by samcmill** [singularityhub/interface#30]
This is valid Dockerfile syntax to set 2 environment variables:

```
ENV A=B X=Y
```

When converting this from Docker to Singularity, the Singularity output is incorrect:

```
%post
A=B=X=Y
%environment
export A=B=X=Y
```

**Comment by vsoch** [comment]
Ditto here! Please post this issue on the spython board and close here --> https://www.github.com/singularityhub/singularity-cli/issues the builder just uses the functions from there to do the conversion. Thank you!
