### ISSUE TITLE
[builder] Named stage conversion

### ISSUE THREAD

**Issue by samcmill** [singularityhub/interface#31]
This is valid Dockerfile syntax to name a layer (for multistage builds):

```
FROM ubuntu:16.04 AS level
```

Singularity has no corresponding concept.  The converter carries it through which results in an invalid Singularity recipe.

```
Bootstrap: docker
From: ubuntu:16.04 AS devel
```

**Comment by vsoch** [comment]
And this one too :)

https://www.github.com/singularityhub/singularity-cli/issues 

We will fix these up!
