### ISSUE TITLE
[builder] chained commands

### ISSUE THREAD

**Issue by samcmill** [singularityhub/interface#32]
It is common in Docker to chain commands together into a single layer and break the command so it does not exceed 80 characters.  For instance:

```
RUN apt-get update -y && \
  apt-get-install -y --no-install-recommends \
     python \
     python3 && \
  rm -rf /var/lib/apt/lists/* 
```

This is converted to Singularity as

```
%post
apt-get update -y && \
apt-get install -y --no-install-recommends \
python \
python3 && \
rm -rf /var/lig/apt/lists/*
```

The builder then interprets this as 5 effective commands rather than 1 long command split over 5 lines.  The builder fails when trying to run `python`.

**Comment by vsoch** [comment]
Ditto here! Please post this issue on the spython board and close here --> https://www.github.com/singularityhub/singularity-cli/issues the builder just uses the functions from there to do the conversion. Thank you!
